auth/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('login/',views.Login.as_view()),
    path('logout/', views.Logout.as_view()),
    path('signup/',views.SignUp.as_view()),
    
]

home/urls.py
from django.urls import path
from home import views
urlpatterns=[
    path('home/',views.Home.as_view()),
    path('post/',views.Post.as_view()),
    path('post/<int:pk>/comment',views.PostComment.as_view()),
    path('post/<int:pk>/like',views.PostLike.as_view()),  #mere pass ek url h jispe mere frontend/user ko bas ek post request bhejni h aur mei uss post ko like kar dunga aur we jusrt want the id and a post request on this url 
    path('',views.Wall.as_view()),
    
]

mediaapp/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("auth.urls")),
    path("", include("home.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now=True)
    content=models.TextField()
    image=models.ImageField(blank=True)
    def __str__(self):
        return self.content[:50]
class Like(models.Model):
    post=models.ForeignKey('Post',on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

class Comment(models.Model):
    post=models.ForeignKey('Post',on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    content=models.CharField(max_length=1024)


class Friends(models.Model):
    person1=models.ForeignKey(User,on_delete=models.CASCADE, related_name='person1')
    person2=models.ForeignKey(User,on_delete=models.CASCADE, related_name='person2')
    

home/forms.py
from django import forms
from home import models

class PostForm(forms.ModelForm):
    class Meta:
        model=models.Post
        fields=['content', 'image']
    def save(self, commit=True):   
        return super().save(commit=commit)


class PostComment(forms.ModelForm):
    class Meta:
        model=models.Comment
        fields=['content']


home/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views.generic.detail import SingleObjectMixin
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q

from home import models, forms

# Create your views here.
class Wall(LoginRequiredMixin, ListView):
  context_object_name = 'posts'
  template_name = 'social/wall.html'
  login_url = 'auth/login'

  def get_queryset(self):
    friendIds = [ friend.person2.id for friend in  models.Friends.objects.filter(person1 = self.request.user) ]
    friendIds = friendIds + [ friend.person1.id for friend in  models.Friends.objects.filter(person2 = self.request.user) ]

    return models.Post.objects.filter(user__in = friendIds).order_by('-created_at')

class Home(LoginRequiredMixin, ListView):
  context_object_name = 'posts'
  template_name = 'social/home.html'
  login_url = 'auth/login'

  def get_queryset(self):
    return models.Post.objects.filter(user = self.request.user)
  
  def get_context_data(self, *args, **kwargs):
    data = super().get_context_data(*args, **kwargs)
    data['post_form'] = forms.PostForm()

    return data

class Post(View):
  def post(self, request):
    form = forms.PostForm(request.POST, request.FILES)
    if form.is_valid():
      post = form.save(commit=False)
      post.user = request.user
      post.save()
    
    return redirect('/home/')

class PostLike(View):
  model = models.Post

  def post(self, request, pk):
    post = self.model.objects.get(pk = pk)
    models.Like.objects.create(post = post, user = request.user)
    return HttpResponse(code = 204)

class PostComment(View):
  model = models.Post
  form = forms.PostComment

  def post(self, request, pk):
    post = self.model.objects.get(pk = pk)
    form = self.form(request.POST)

    if form.is_valid():
      comment = form.save(commit = False)
      comment.post = post
      comment.user = request.user
      comment.save()
      return HttpResponse(code = 204)
    
    print(form.errors)
    return HttpResponse('Error')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<title>HOME PAGE</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">

<link rel="stylesheet" href="{% static 'css/home.css' %}">

<body id="main">
    <!--navbar-->
    <header>
        <nav id="header-nav" class="navbar navbar-default navbar-dark bg-primary">
            <div class="container">
                <div class="navbar-header">
                    <div class="navbar-brand">
                        <a href="homepage.html">
                            <h1>F.R.I.E.N.D.S<br></h1>
                        </a>
                        <h3>The one stop destination for socialising</h3>
                    </div>
                    <div id="mySidebar" class="sidebar">

                        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                        <li><a href="/home">Home</a></li>
                        <li><a href="/wall">Wall</a></li>

                        <li><a href="/auth/logout">Sign Out</a></li>

                    </div>
                    <div class="visible-xs">
                        <button class="openbtn" onclick="openNav()">&#9776; Menu</button>
                    </div>
                    <!-- {% if user.is_authenticated %} -->

                    <div class="hidden-xs">
                        <!-- <li><a href="/home">Hello, {{  user.first_name }} {{ user.last_name }}</a></li> -->
                        <button type="button" class="btn pos1 login btn-info">Sign Out</button>
                    </div>

                    <div class="hidden-xs">
                        <ul id="nav-list" class="nav navbar-nav navbar-right">
                            <li class="active">
                                <a href="/home">Home</a>
                            </li>
                            <li>
                                <a href="/home">Wall</a>
                            </li>
                        </ul>
                    </div>
                    <!-- {% else %} -->
                    <div class="hidden-xs">
                        <!-- <li><a href="/home">Hello, {{  user.first_name }} {{ user.last_name }}</a></li> -->
                        <button type="button" class="btn pos1 login btn-info">Login</button>
                    </div>
                    <!-- {% endif %} -->

                </div>
            </div>
        </nav>
    </header>

    {% block content %}  {% endblock %}
    
    <footer class="foot">
        <h4>Footer content</h4>
        <button type="button" class="btn butn2 hover-skyblue btn-link"><a href="#"> facebook page</a></button>
        <button type="button" class="btn butn2 hover-skyblue btn-link"><a href="#"> insta page</a></button>
    </footer>
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/social.js' %}"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('.modal');
            var instances = M.Modal.init(elems, {});
        });
    </script>
</body>

</html>

templates/social/components/post.html
<section class="row">
    <div class="col-xs-2 col-sm-3 col-md-3"></div>
    <div class="col-xs-8 col-sm-6 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading " id="hd">Post by @{{post.user.first_name }} {{ post.user.last_name }}</div>
            {% if post.image %}
            <img class="card-img-top" src="/media/{{ post.image }}" style="width: 25%;" alt="Card image cap">
            {% endif %}
            <div class="panel-body textcard">{{ post.content }}
                <p class="right"><button href="#" class="btn btn-primary btncard" onclick="likePost({{post.id}})">Like</button>
                    <button class="modal-trigger btn btn-primary btncard" href="#postModal{{post.id}}">Comment</button>
                </p>
            </div>
            <div class="panel-footer">{{ post.like_set.count }} Likes &#8281;{{ post.comment_set.count }} comments</div>
        </div>
        <div class="col-xs-2 col-sm-3 col-md-3"></div>
</section>


<div id="postModal{{post.id}}" class="modal">
    <div class="modal-content">
      <h4>Comments</h4>
      <ul>
        {% for comment in post.comment_set.all %}
          <li>{{ comment.user.first_name }} - {{ comment.content }}</li>
        {% endfor %}
      </ul>
      <form onsubmit="commentPost({{post.id}}, document.getElementById('comment{{post.id}}').value);">
        <div class="input-field">
          <input id="comment{{post.id}}" type="text" class="validate">
          <label for="comment{{post.id}}">Comment</label>
          <button type="submit" class="btn btn-primary btncard">Submit</button>
        </div>
      </form>
    </div>
  </div>
  

templates/social/home.html
{% extends 'base.html' %}

{% block content %}
<section class="row">
    <div class="col-xs-2 col-sm-3 col-md-3"></div>
    <div class="col-xs-8 col-sm-6 col-md-6">

        <form action="/post/" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ post_form }}

            <button type="submit" class="btn btn-primary btncard">Post</button>
        </form>

    </div>
    <div class="col-xs-2 col-sm-3 col-md-3"></div>

</section>
{% for post in posts %}
<section class="row">
    <div class="col-xs-2 col-sm-3 col-md-3"></div>
    <div class="col-xs-8 col-sm-6 col-md-6">

        {% include 'social/components/post.html' %}

    </div>
    <div class="col-xs-2 col-sm-3 col-md-3"></div>

</section>
{% endfor %}

{% endblock %}

templates/social/wall.html
{% extends 'base.html' %}

{% block content %}
{% for post in posts %}
<section class="row">
    <div class="col-xs-2 col-sm-3 col-md-3"></div>
    <div class="col-xs-8 col-sm-6 col-md-6">
        <div class="panel panel-default">
            {% include 'social/components/post.html' %}
        </div>
    </div>

    <div class="col-xs-2 col-sm-3 col-md-3"></div>
</section>
{% endfor %}
{% endblock %}